### ISSUE TITLE
Reasignacion de los casos de uso a cada miembro del proyecto

### ISSUE THREAD

**Issue by dani-am** [dani-am/2022-ISO2-B01#10]
Se delega en @GuillermoCuberoCharco la nueva asignación de los casos de uso a cada uno de los miembros del proyecto.

**Comment by GuillermoCuberoCharco** [comment]
Durante el desarrollo del proyecto cada caso de uso representara una interacción de la aplicación y a cada miembro del grupo se le repartirá de la forma más igualada posible un tiempo de trabajo en cada fase de la interacción. Sin embargo, cada iteración será dirigida por un miembro del grupo, de forma que todos dirijan al menos un Caso de Uso, aunque todos trabajen en el desarrollo del mismo.

A continuación la asignación de Coordinadores de cada Iteración:
- CU.1. Registro en la aplicación: Daniel
- CU.2. Modificación  de dueños: Rodrigo
- CU.3. Creación de  Ofertas: Guillermo
- CU.4. Planificación  de la ruta: Yolanda
- CU.5. Añadir  comentarios: Angela
- CU.6. Análisis de  reseñas: Mario
