### ISSUE TITLE
Elicitación de requisitos del sistema

### ISSUE THREAD

**Issue by dani-am** [dani-am/2022-ISO2-B01#2]
**Descripción del Issue**
Creación de entre 10 a 12 casos de uso (2 por equipo) para su discusión en la próxima reunión del 26/10/2022. 

**Miembros involucrados**
Ángela Gijón - @Angelagf24 
Mario Serrano - @mariosr13 

**Fecha estimada de finalización**
Hasta el 26/10/2022. Día incluído.

**Comment by mariosr13** [comment]
[Requisitos trabajo.docx](https://github.com/dani-am/2022-ISO2-B01/files/9868579/Requisitos.trabajo.docx)

**Comment by Angelagf24** [comment]
Estarían los requisitos de los peregrinos y los de los dueños de hostales, restaurantes, paradas de interés turístico…
Requisitos de los dueños de negocios:
1.	Añadir un negocio o su información. 
2.	Borrar un negocio o su información.
3.	Editar un negocio o su información.
4.	Mostar un negocio o su información.
5.	Hacer ofertas a los peregrinos de la red.
6.	Leer los comentarios que pongan los peregrinos.
7.	Responder los comentarios que pongan los peregrinos.
Requisitos de los peregrinos:
1.	Planificar las etapas de su camino en función de sus recursos y su tiempo disponible.
2.	Mostrar información de distintos caminos
3.	Buscar diferentes recursos cercanos a la posición en la que se encuentren o buscando un punto de destino.
4.	Mostar información sobre la etapa en curso y las restantes.
5.	Añadir comentarios a los negocios
6.	Hacer un blog sobre el camino recorrido donde se pueden compartir varias cosas como las fotos.
Requisitos no funcionales:
1.	Número de negocios
2.	Número de peregrinos que están usando la aplicación.
3.	Numero de peregrinos que están satisfechos (al menos 4 estrellas en sus comentarios).
4.	Análisis de las reseñas mas importantes de los peregrinos sobre los negocios visitados para posteriormente promocionarlos.

Cada requisito corresponde a un Caso de Uso. En la wiki estimamos unos requisitos de entre 6 y 12 por lo que en la reunión decidiremos cuales descartamos.

**Comment by Angelagf24** [comment]
**ACTUALIZACIÓN DE REQUISITOS A CASOS DE USO TRAS LA REUNIÓN DEL MIÉRCOLES 26/10/22**
Requisito 1,2,3,4 de los dueños se unifican en un solo caso de uso. (modificación de dueños sobre negocios)
Requisito 6 y 7 de los dueños se unifican (leer y responder comentarios).
Requisitos 2 y 3 de los peregrinos se unifican en un solo caso de uso.
De los requisitos no funcionales se juntan el 2 y 3 como su el 3 fuese un filtro del 2.
PRIORIDADES: 
1.	Caso de uso 1, modificación de dueños.
2.	Caso de uso 2, planificación de la ruta.
3.	Caso de uso 3, creación de ofertas.
4.	Caso de uso 4, mostrar información de distintos caminos
5.	Caso de uso 5, buscar recursos según la ubicación y mostrar información.
6.	Caso de uso 6, añadir comentarios.
7.	Caso de uso 7, leer y responder los comentarios de los peregrinos.
8.	Caso de uso 8, análisis de reseñas.
9.	Caso de uso 9, número de peregrinos (y los satisfechos).
Caso de uso 10 de los no funcionales, número de negocios.
