### ISSUE TITLE
Elaboración de supuestos de gestión de tiempo y cálculo de costes

### ISSUE THREAD

**Issue by dani-am** [dani-am/2022-ISO2-B01#3]
**Descripción del Issue**
Creación de supuestos, entre 5 y 6, para la aplicación de la gestión de tiempo y cálculo de costes.

**Miembros involucrados**
Yolanda Galván - @YolandaGR13 
Guillermo Cubero - @GuillermoCuberoCharco 

**Fecha estimada de finalización**
Hasta el 26/10/2022. Día incluído.

**Comment by YolandaGR13** [comment]
[Supuesto.docx](https://github.com/dani-am/2022-ISO2-BC1/files/9863611/Supuesto.docx)

**Comment by YolandaGR13** [comment]
Dia 25/10/2022 hora 17:00h
 
                         
Supuestos : 

La semana 40 h, suponemos que cada miembro de la empresa trabaja de forma equitativa 6h40 a la semana 
No se trabaja en festivos y no hay guardias
No se empieza una iteracion nueva en el mismo dia que se acaba otra 
El jefe cobra 40€/h es decir 1040€ al mes
El secretario 37€ es decir 962€ al mes
El resto 35€/h es decir 910€ al mes 
No todos sabemos lo mismo y la repartición de tareas queda en manos del jefe 

La reunión ha durado 34 min

**Comment by YolandaGR13** [comment]
Dia 03/11/2022

Supuestos corregidos:

La semana 40 h, suponemos que cada miembro de la empresa trabaja de forma equitativa 6h40 a la semana
No se trabaja en festivos y no hay guardias
Se empieza una iteracion nueva en el mismo dia que se acaba otra
El jefe cobra 40€/h es decir 1040€ al mes
El secretario 37€ es decir 962€ al mes
El resto 35€/h es decir 910€ al mes
Todos sabemos lo mismo y el jefe es quien determina quien hace cada tarea
