### ISSUE TITLE
Elaboración actas reunión

### ISSUE THREAD

**Issue by dani-am** [dani-am/2022-ISO2-B01#4]
**Descripción del Issue**
Documentación de las conclusiones sacadas en las reuniones. Se deberá elaborar un documento que posteriormente se le pasará al representante, el cual lo añadirá a la wiki.

**Miembros involucrados**

- El secretario Guillermo Cubero - @GuillermoCuberoCharco

**Fecha estimada de finalización**
Enero 2023.

**Comment by GuillermoCuberoCharco** [comment]
**Iteración 0**
21/10/2022

**Presentes:** 
- Daniel 
- Angela
- Mario 
- Yolanda 

**Ausentes:**
- Guillermo (Trabajo)
- Rodrigo (Motivos externos)
 
**Temas discutidos:**
- Creación del grupo en GitHub 
- Elaboración correcta de la wiki/GitHub: Daniel Y Rodrigo 
- Creación de supuestos: Yolanda y Guillermo
- Análisis de requisitos: Mario y Angela

**Fecha límite para completar los requisitos del acta: 26/10/2022**

**Temas a discutir:**
- Casos de Uso
- Estimación de Costes/Esfuerzo

**Apuntes a tener en cuenta:**
1. Yolanda esta haciendo el acta porque Guillermo no esta 
2. Falta todavía una implementación/código que no se ha subido a campus virtual 
3. Estimamos supuestos: 5-6 
4. Estimamos requisitos: 10-12

**Próxima reunión el 26/10/2022 a las 11:30 en la Alu**

**Comment by GuillermoCuberoCharco** [comment]
**Iteración 0**
26/10/2022

**Presentes:**

Daniel
Angela
Mario
Yolanda
Guillermo
Rodrigo

**Temas discutidos:**
- Selección de Casos de Uso, reducido a 12 casos
- Asignación de prioridades a los Casos de Uso
- Asignación de Casos de Uso a cada miembro
- Estimación de Iteraciones futuras 11 (10 por Casos de Uso y la final)
- Asumimos unos costes de 1000€ en Recursos Humanos y 500€ en facturas por Iteración 
- Determinación de habilidades de cada miembro del grupo

**Asignación de Casos de Uso:**
- CU_1: Yolanda, Guillermo
- CU_2: Rodrigo, Dani
- CU_3: Mario, Angela
- CU_4: Angela, Mario
- CU_5: Dani, Rodrigo
- CU_6: Guillermo, Yolanda
- CU_7:Angela, Mario
- CU_8: Mario. Angela
- CU_9: Rodrigo, Dani
- CU_10: Yolanda, Guillermo

**Temas a discutir:**
- Habilidades de cada miembro del grupo (Dani y Rodrigo)
- Completar Tablas de Fases del Proyecto (Angela y Mario)
- Corrección de Supuestos (Yolanda y Guillermo)

**Fecha límite para completar los requisitos del acta: 4/1/2022**


**Próxima reunión el 4/11/2022 a las 11:30 en la Alu**

**Comment by GuillermoCuberoCharco** [comment]
**Iteración 0**
10/11/2022

**Presentes:**

Daniel
Angela
Mario
Yolanda
Guillermo
Rodrigo

**Temas discutidos:**
- Reparto del Trabajo Teórico
- Fecha de unión del trabajo: 23/11/2022
- Revisión de las Tablas de Fases del Proyecto
- Adjuntar control de Versiones a todos los documentos
- Planificación del Maiven hecha

**Temas a discutir:**
- Planificación temporal

**Fecha límite para completar los requisitos del acta: 16/1/2022**

**Próxima reunión el 16/11/2022 a las 11:30 en la Alu**

**Comment by GuillermoCuberoCharco** [comment]
**Iteración 0**
15/11/2022

**Presentes:**

Daniel
Angela
Yolanda
Guillermo
Rodrigo

**Temas discutidos:**
- Replanificación del proyecto
- Reasignación de Casos de Uso
- Actualización de versiones
- Corrección de Diagramas de Casos
- Corrección de Tablas del proyecto

**Temas a discutir:**
- Creación de ramas auxiliares por iteración
- Restructuración del modo de trabajo

**Fecha límite para completar los requisitos del acta: 16/1/2022**

**Próxima reunión el 16/11/2022 a las 11:30 en la Alu**
