### ISSUE TITLE
Creación de las tablas de fase del proyecto

### ISSUE THREAD

**Issue by dani-am** [dani-am/2022-ISO2-B01#5]
**Descripción del Issue**
Creación de las tablas de fase del proyecto

**Miembros involucrados**

- Ángela - @Angelagf24 
- Mario - @mariosr13 

**Fecha estimada de finalización**
Día 2/11/2022

**Comment by Angelagf24** [comment]
[Tablas.docx](https://github.com/dani-am/2022-ISO2-B01/files/9917682/Tablas.docx)

**Comment by Angelagf24** [comment]
![image](https://user-images.githubusercontent.com/91559952/199430367-c8921287-047d-4207-960b-e677227e7fbe.png)
![image](https://user-images.githubusercontent.com/91559952/199430442-a1ea4976-3bc5-4018-a0b4-342084b5c93a.png)
![image](https://user-images.githubusercontent.com/91559952/199430522-2a7e1bee-5f87-4abd-a413-1f28eac3f812.png)

*Estimamos que lo que cobra un trabajador es 30 Euros (media de un trabajador medio, el secretario y el jefe) para el cálculo del coste.

**Comment by GuillermoCuberoCharco** [comment]
**Actualización de las tablas**
**Versión: 0.2**

![Tabla1_Requisitos funcionales](https://user-images.githubusercontent.com/91546381/201991184-9f820bf1-84b7-4c5a-a361-8568f396635f.JPG)
![Tabla2_Casos de Uso](https://user-images.githubusercontent.com/91546381/201991327-371d8735-d05d-4bcf-82fa-9624b98827d5.JPG)
![Tabla3](https://user-images.githubusercontent.com/91546381/201991250-d55c60cb-04f8-4944-baba-344bc84e1d42.JPG)
4.JPG)
