### ISSUE TITLE
Restructuración del proyecto

### ISSUE THREAD

**Issue by dani-am** [dani-am/2022-ISO2-B01#7]
Considerado:

El equipo ha decidido que:

**Comment by GuillermoCuberoCharco** [comment]
Casos de Uso (Versión 0.2)
- Caso de Uso 1: Modificación de Dueños.
- Caso de Uso 2: Registro en la aplicación.
- Caso de Uso 3: Análisis de reseñas.
- Caso de Uso 4: Añadir comentarios.
- Caso de Uso 5: Creación de Ofertas.
- Caso de Uso 6: Planificación de la ruta.
